### ISSUE TITLE
cannot run ./ruby check-kafka-ping.rb -h

### ISSUE THREAD

**Issue by natpavin** [sensu-plugins/sensu-plugins-kafka2#4]
when i run

./ruby check-kafka-ping.rb -h i found "/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sensu-plugins-kafka (LoadError)
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-kafka2-0.0.1/bin/check-kafka-ping.rb:31:in `<top (required)>'
	from check-kafka-ping.rb:22:in `load'
	from check-kafka-ping.rb:22:in `<main>'"

if i install sensu-plugins-kafka2 then i got a message overwrite some file and can't run same

**Comment by stefan-as** [comment]
Same for `metrics-kafka-http.rb`:

```
./metrics-kafka-http.rb 
/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sensu-plugins-kafka (LoadError)
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-kafka2-0.0.1/bin/metrics-kafka-http.rb:32:in `<top (required)>'
	from /opt/sensu/embedded/bin/metrics-kafka-http.rb:22:in `load'
	from /opt/sensu/embedded/bin/metrics-kafka-http.rb:22:in `<main>'
```

Package name `sensu-plugins-kafka2` does not match includes `sensu-plugins-kafka`.

**Comment by macropin** [comment]
I have reproduced both errors. It seems `metrics-kafka-http.rb` and `check-kafka-ping.rb` are both broken. However `check-topic.rb` works.

**Comment by natpavin** [comment]
I have edit /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-kafka2-0.0.1/bin/check-kafka-ping.rb

see as below

######################################

require 'sensu-plugin/check/cli'
require 'rest-client'
require 'json'
require 'sensu-plugins-kafka2'
#require 'sensu-plugins-kafka'

class CheckKafkaPing < Sensu::Plugin::Check::CLI
  include CommonKafka2

  option :endpoint,
         short: '-p ENDPOINT',
         long: '--endpoint ENDPOINT',
         description: 'kafka.http.metrics Endpoint',
         default: 'http://localhost:8897/api/ping'

  def run
    result = request
    if result.to_s.strip == 'pong'
      ok 'Kafka is UP'
    elsif result == 'DOWN'
      warning 'Kafka is DOWN'
    end
  rescue StandardError => e
    critical e.message
  end
end

######################################

And It already use check-kafka-ping.rb all the same
